sudo: false
language: node_js
node_js:
    - "10"
    - "13"
cache:
    directories:
        - node_modules
jobs:
    include:
      - stage: "ESLint"
        script: yarn eslint
script:
    - yarn build